### ISSUE TITLE
make all fb media supported sir

### ISSUE THREAD

**Issue by iegl3** [MR-NAYAN-404/nayan-media-downloader#1]
such as reels, images, etc? i think that will be helpful

**Comment by MR-NAYAN-404** [comment]
Already created bro use fbdown

**Comment by iegl3** [comment]
> Already created bro use fbdown

okay its worked sir, btw is gdrive and pinterest downloader worked well? i always got link url not valid, sir.. can you specify the example of valid url, sir?
